Document: shadowvpn
Title: Debian shadowvpn Manual
Author: <insert document author here>
Abstract: This manual describes what shadowvpn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shadowvpn/shadowvpn.sgml.gz

Format: postscript
Files: /usr/share/doc/shadowvpn/shadowvpn.ps.gz

Format: text
Files: /usr/share/doc/shadowvpn/shadowvpn.text.gz

Format: HTML
Index: /usr/share/doc/shadowvpn/html/index.html
Files: /usr/share/doc/shadowvpn/html/*.html
