.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 mark <cqcq233@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SHADOWVPN 8 "October 16, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
shadowvpn \- A fast, safe VPN based on libsodium
.SH SYNOPSIS
.B shadowvpn
\-c config_file [\-s start/stop/restart] [\-v] 
.br
.SH DESCRIPTION
.B shadowvpn
is a fast, safe VPN based on libsodium. Designed for low end devices, i.e. OpenWRT routers.
.SH OPTIONS
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-s,  start/stop/restart
control shadowvpn process. if omitted, will run in foreground
.TP
.B \-c config_file 
path to config file
.TP
.B \-v
 verbose logging
.SH SEE ALSO
.br
The programs are documented fully by
.IR "Clowwindy <clowwindy42@gmail.com>"
.br
You can find all the documentation in the wiki: https://github.com/clowwindy/ShadowVPN/wiki

